// src/components/Dashboard.js
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardActions from '@mui/material/CardActions';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import IconButton from '@mui/material/IconButton';
import Divider from '@mui/material/Divider';
import Paper from '@mui/material/Paper';
import Dialog from '@mui/material/Dialog';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogContentText from '@mui/material/DialogContentText';
import DialogTitle from '@mui/material/DialogTitle';
import CircularProgress from '@mui/material/CircularProgress'; // Added back for loading state
import AddIcon from '@mui/icons-material/Add';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import EditIcon from '@mui/icons-material/Edit';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import WarningIcon from '@mui/icons-material/Warning';

import apiService from '../utils/apiService'; // Uses refactored service

function Dashboard() {
  const navigate = useNavigate();
  const [agents, setAgents] = useState([]);
  const [loading, setLoading] = useState(true); // Keep loading state
  const [error, setError] = useState(null);

  // State for delete confirmation
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [agentToDelete, setAgentToDelete] = useState(null);

  // Fetch agent configurations when component mounts
  useEffect(() => {
    fetchAgentConfigs();
  }, []);

  // Function to fetch agent configurations from local storage via apiService
  const fetchAgentConfigs = async () => {
    try {
      setLoading(true);
      // apiService.getAgents now returns locally stored configurations
      const agentConfigs = await apiService.getAgents();
      setAgents(agentConfigs);
      setError(null);
    } catch (err) {
      console.error('Error fetching agent configurations:', err);
      setError('Failed to load agent configurations. ' + (err.message || ''));
    } finally {
      setLoading(false);
    }
  };

  // Function to navigate to the test page for this agent config
  const handleRunAgent = (agentId) => {
    navigate(`/test/${agentId}`);
  };

  // Function to navigate to the builder with this agent config loaded
  const handleEditAgent = (agentId) => {
    navigate(`/build/${agentId}`);
  };

  // Function to handle cloning an agent configuration
  const handleCloneAgent = (agentId) => {
    const agentToClone = agents.find(agent => agent.id === agentId);
    if (agentToClone) {
      // Create a new config based on the existing one, removing ID/timestamps
      const clonedAgentConfig = {
        ...agentToClone,
        name: `${agentToClone.name} (Clone)`,
        id: undefined, // Remove ID so a new one will be generated by apiService
        created_at: undefined,
        updated_at: undefined,
        last_used: undefined,
        lastUsed: 'Never'
      };

      // Store in session storage for the builder to pick up
      sessionStorage.setItem('agent_to_edit', JSON.stringify(clonedAgentConfig));
      navigate('/build'); // Navigate to create new agent page
    }
  };

  // Function to initiate deleting an agent configuration
  const handleDeleteAgent = (agentId) => {
    setAgentToDelete(agentId);
    setDeleteDialogOpen(true);
  };

  // Function to confirm agent configuration deletion (local only)
  const confirmDeleteAgent = async () => {
    if (!agentToDelete) return;

    try {
      setLoading(true); // Indicate activity
      // Call the API service to delete the local config
      const success = await apiService.deleteAgent(agentToDelete);

      if (success) {
        // Remove from local state immediately for UI update
        setAgents(prevAgents => prevAgents.filter(agent => agent.id !== agentToDelete));
        setError(null);
      } else {
         setError('Failed to delete agent configuration.');
      }

      setDeleteDialogOpen(false);
      setAgentToDelete(null);
    } catch (error) {
      console.error('Error deleting agent configuration:', error);
      setError('Failed to delete agent configuration: ' + (error.message || ''));
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container maxWidth="lg" sx={{ mt: 4, mb: 8 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
        <Typography variant="h4" component="h1">
          Your Agent Configurations {/* UPDATED Text */}
        </Typography>
        <Button
          variant="contained"
          startIcon={<AddIcon />}
          size="large"
          onClick={() => navigate('/build')}
        >
          Create Agent Config {/* UPDATED Text */}
        </Button>
      </Box>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', my: 8 }}>
          <CircularProgress /> {/* Show loading indicator */}
        </Box>
      ) : error ? (
        <Alert severity="error" sx={{ my: 4 }}>{error}</Alert>
      ) : (
        <Grid container spacing={3}>
          {/* Map over agent configurations */}
          {agents.map((agent) => (
          <Grid item xs={12} md={4} key={agent.id}>
            <Card className="card" sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
              <CardContent sx={{ flexGrow: 1 }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                  <Typography variant="h6" component="h2" noWrap title={agent.name}>
                    {agent.name}
                  </Typography>
                  {/* Display the selected Google model */}
                  <Chip
                    label={agent.model || 'N/A'}
                    size="small"
                    color="primary" // Consider changing color based on model type?
                    variant="outlined"
                    title={`Model: ${agent.model}`}
                  />
                </Box>

                <Typography variant="body2" color="text.secondary" sx={{ mb: 2, height: '3em', overflow: 'hidden', textOverflow: 'ellipsis', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' }}>
                  {agent.description || 'No description provided.'}
                </Typography>

                <Typography variant="caption" color="text.secondary">
                  Tools Configured:
                </Typography>
                <Box sx={{ mt: 1, height: '3em', overflow: 'hidden' }}>
                  {agent.tools && agent.tools.length > 0 ? agent.tools.map((tool, index) => (
                    <Chip
                      key={index}
                      label={tool.name || tool.id || 'Unknown Tool'} // Display name or ID
                      size="small"
                      sx={{ mr: 0.5, mb: 0.5 }}
                      title={tool.description || tool.name}
                    />
                  )) : <Typography variant="caption" sx={{ fontStyle: 'italic' }}>None</Typography>}
                </Box>
              </CardContent>

              <Divider />

              <CardActions sx={{ justifyContent: 'space-between', p: 1 }}>
                {/* Run button navigates to test page */}
                <Button
                  size="small"
                  startIcon={<PlayArrowIcon />}
                  color="primary"
                  onClick={() => handleRunAgent(agent.id)}
                  title="Test this agent configuration"
                >
                  Test
                </Button>

                <Box>
                  {/* Edit button navigates to builder */}
                  <IconButton
                    size="small"
                    color="primary"
                    title="Edit Configuration"
                    onClick={() => handleEditAgent(agent.id)}
                  >
                    <EditIcon fontSize="small" />
                  </IconButton>
                  {/* Clone button */}
                  <IconButton
                    size="small"
                    color="primary"
                    title="Clone Configuration"
                    onClick={() => handleCloneAgent(agent.id)}
                  >
                    <ContentCopyIcon fontSize="small" />
                  </IconButton>
                  {/* Delete button */}
                  <IconButton
                    size="small"
                    color="error"
                    title="Delete Configuration"
                    onClick={() => handleDeleteAgent(agent.id)}
                  >
                    <DeleteOutlineIcon fontSize="small" />
                  </IconButton>
                </Box>
              </CardActions>

              {/* Display last used time */}
              <Box sx={{ px: 2, py: 1, bgcolor: 'grey.50', borderTop: '1px solid', borderColor: 'divider' }}>
                <Typography variant="caption" color="text.secondary">
                  Last tested: {agent.lastUsed || 'Never'}
                </Typography>
              </Box>
            </Card>
          </Grid>
        ))}

        {/* "Create New" Card */}
        <Grid item xs={12} md={4}>
          <Paper
            sx={{
              height: '100%',
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
              p: 4,
              borderRadius: 2,
              border: '2px dashed',
              borderColor: 'grey.300',
              bgcolor: 'background.paper',
              cursor: 'pointer',
              '&:hover': { borderColor: 'primary.main' }
            }}
            elevation={0}
            onClick={() => navigate('/build')}
          >
            <IconButton
              color="primary"
              sx={{ mb: 2, p: 2, bgcolor: 'primary.light', color: 'white' }} // Adjust colors if needed
            >
              <AddIcon fontSize="large" />
            </IconButton>
            <Typography variant="h6" component="div" align="center">
              Create New Agent Config {/* UPDATED Text */}
            </Typography>
            <Typography variant="body2" color="text.secondary" align="center">
              Define a new agent configuration
            </Typography>
          </Paper>
        </Grid>
        </Grid>
      )}

      {/* Delete Confirmation Dialog */}
      <Dialog
        open={deleteDialogOpen}
        onClose={() => setDeleteDialogOpen(false)}
      >
        <DialogTitle sx={{ display: 'flex', alignItems: 'center' }}>
          <WarningIcon color="warning" sx={{ mr: 1 }} />
          Confirm Delete
        </DialogTitle>
        <DialogContent>
          <DialogContentText>
            Are you sure you want to delete this agent configuration? This action cannot be undone.
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDeleteDialogOpen(false)}>
            Cancel
          </Button>
          <Button
            onClick={confirmDeleteAgent}
            color="error"
            variant="contained"
            disabled={loading} // Disable while delete is in progress
          >
            {loading ? <CircularProgress size={20} color="inherit"/> : 'Delete'}
          </Button>
        </DialogActions>
      </Dialog>
    </Container>
  );
}

export default Dashboard;